In [83]:
import pandas as pd
import numpy as np

df = pd.read_csv("../Dataset/SampleSuperstore.csv")

df.head()

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164

In [84]:
df.shape

(9994, 13)

In [85]:
df.columns

Index(['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Postal Code',
       'Region', 'Category', 'Sub-Category', 'Sales', 'Quantity', 'Discount',
       'Profit'],
      dtype='str')

In [86]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Ship Mode     9994 non-null   str
 1   Segment       9994 non-null   str
 2   Country       9994 non-null   str
 3   City          9994 non-null   str
 4   State         9994 non-null   str
 5   Postal Code   9994 non-null   int64
 6   Region        9994 non-null   str
 7   Category      9994 non-null   str
 8   Sub-Category  9994 non-null   str
 9   Sales         9994 non-null   float64
 10  Quantity      9994 non-null   int64
 11  Discount      9994 non-null   float64
 12  Profit        9994 non-null   float64
dtypes: float64(3), int64(2), str(8)
memory usage: 1015.1 KB
None

In [87]:
print(df.isnull().sum())

Ship Mode       0
Segment         0
Country         0
City            0
State           0
Postal Code     0
Region          0
Category        0
Sub-Category    0
Sales           0
Quantity        0
Discount        0
Profit          0
dtype: int64

In [88]:
print(df.duplicated().sum())

17

In [89]:
df.dtypes

Ship Mode           str
Segment             str
Country             str
City                str
State               str
Postal Code       int64
Region              str
Category            str
Sub-Category        str
Sales           float64
Quantity          int64
Discount        float64
Profit          float64
dtype: object

In [90]:
print(df.describe())

        Postal Code         Sales     Quantity     Discount       Profit
count   9994.000000   9994.000000  9994.000000  9994.000000  9994.000000
mean   55190.379428    229.858001     3.789574     0.156203    28.656896
std    32063.693350    623.245101     2.225110     0.206452   234.260108
min     1040.000000      0.444000     1.000000     0.000000 -6599.978000
25%    23223.000000     17.280000     2.000000     0.000000     1.728750
50%    56430.500000     54.490000     3.000000     0.200000     8.666500
75%    90008.000000    209.940000     5.000000     0.200000    29.364000
max    99301.000000  22638.480000    14.000000     0.800000  8399.976000

In [91]:
print(df.head())

        Ship Mode    Segment        Country             City       State  \
0    Second Class   Consumer  United States        Henderson    Kentucky
1    Second Class   Consumer  United States        Henderson    Kentucky
2    Second Class  Corporate  United States      Los Angeles  California
3  Standard Class   Consumer  United States  Fort Lauderdale     Florida
4  Standard Class   Consumer  United States  Fort Lauderdale     Florida

   Postal Code Region         Category Sub-Category     Sales  Quantity  \
0        42420  South        Furniture    Bookcases  261.9600         2
1        42420  South        Furniture       Chairs  731.9400         3
2        90036   West  Office Supplies       Labels   14.6200         2
3        33311  South        Furniture       Tables  957.5775         5
4        33311  South  Office Supplies      Storage   22.3680         2

   Discount    Profit
0      0.00   41.9136
1      0.00  219.5820
2      0.00    6.8714
3      0.45 -383.0310
4      0.20    2.5164

In [92]:
print(df.tail())

           Ship Mode   Segment        Country         City       State  \
9989    Second Class  Consumer  United States        Miami     Florida
9990  Standard Class  Consumer  United States   Costa Mesa  California
9991  Standard Class  Consumer  United States   Costa Mesa  California
9992  Standard Class  Consumer  United States   Costa Mesa  California
9993    Second Class  Consumer  United States  Westminster  California

      Postal Code Region         Category Sub-Category    Sales  Quantity  \
9989        33180  South        Furniture  Furnishings   25.248         3
9990        92627   West        Furniture  Furnishings   91.960         2
9991        92627   West       Technology       Phones  258.576         2
9992        92627   West  Office Supplies        Paper   29.600         4
9993        92683   West  Office Supplies   Appliances  243.160         2

      Discount   Profit
9989       0.2   4.1028
9990       0.0  15.6332
9991       0.2  19.3932
9992       0.0  13.3200
9993       0.0  72.9480

In [93]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 17

In [94]:
df = df.drop_duplicates()
print("Duplicate rows after cleaning:", df.duplicated().sum())

Duplicate rows after cleaning: 0

In [95]:
print(df.isnull().sum())

Ship Mode       0
Segment         0
Country         0
City            0
State           0
Postal Code     0
Region          0
Category        0
Sub-Category    0
Sales           0
Quantity        0
Discount        0
Profit          0
dtype: int64

In [96]:
print("Sales <= 0--->", (df["Sales"] <= 0).sum())
print("Quantity <= 0--->", (df["Quantity"] <= 0).sum())
print("Discount < 0--->", (df["Discount"] < 0).sum())
print("Discount > 1--->", (df["Discount"] > 1).sum())

Sales <= 0---> 0
Quantity <= 0---> 0
Discount < 0---> 0
Discount > 1---> 0

In [97]:
print("Ship Modes:")
print(df["Ship Mode"].unique())
print()
print("Segments:")
print(df["Segment"].unique())
print()
print("Regions:")
print(df["Region"].unique())
print()
print("Categories:")
print(df["Category"].unique())

Ship Modes:
<StringArray>
['Second Class', 'Standard Class', 'First Class', 'Same Day']
Length: 4, dtype: str

Segments:
<StringArray>
['Consumer', 'Corporate', 'Home Office']
Length: 3, dtype: str

Regions:
<StringArray>
['South', 'West', 'Central', 'East']
Length: 4, dtype: str

Categories:
<StringArray>
['Furniture', 'Office Supplies', 'Technology']
Length: 3, dtype: str

In [98]:
print(df["Sub-Category"].unique())

<StringArray>
[  'Bookcases',      'Chairs',      'Labels',      'Tables',     'Storage',
 'Furnishings',         'Art',      'Phones',     'Binders',  'Appliances',
       'Paper', 'Accessories',   'Envelopes',   'Fasteners',    'Supplies',
    'Machines',     'Copiers']
Length: 17, dtype: str

In [99]:
text_columns = df.select_dtypes(include="str").columns

for column in text_columns:
    print(column, (df[column] != df[column].str.strip()).sum())

Ship Mode 0
Segment 0
Country 0
City 0
State 0
Region 0
Category 0
Sub-Category 0

In [100]:
print(df[["Sales", "Quantity", "Discount", "Profit"]].describe())

              Sales     Quantity     Discount      Profit
count   9977.000000  9977.000000  9977.000000  9977.00000
mean     230.148902     3.790719     0.156278    28.69013
std      623.721409     2.226657     0.206455   234.45784
min        0.444000     1.000000     0.000000 -6599.97800
25%       17.300000     2.000000     0.000000     1.72620
50%       54.816000     3.000000     0.200000     8.67100
75%      209.970000     5.000000     0.200000    29.37200
max    22638.480000    14.000000     0.800000  8399.97600

In [101]:
df.nlargest(10, "Sales")[[
    "City",
    "State",
    "Region",
    "Category",
    "Sub-Category",
    "Sales",
    "Quantity",
    "Discount",
    "Profit"
]]

,City,State,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
2697,Jacksonville,Florida,South,Technology,Machines,22638.480,6,0.5,-1811.0784
6826,Lafayette,Indiana,Central,Technology,Copiers,17499.950,5,0.0,8399.9760
8153,Seattle,Washington,West,Technology,Copiers,13999.960,4,0.0,6719.9808
2623,New York City,New York,East,Technology,Copiers,11199.968,4,0.2,3919.9888
4190,Newark,Delaware,East,Technology,Copiers,10499.970,3,0.0,5039.9856
9039,Detroit,Michigan,Central,Office Supplies,Binders,9892.740,13,0.0,4946.3700
4098,Minneapolis,Minnesota,Central,Office Supplies,Binders,9449.950,5,0.0,4630.4755
4277,Lakewood,New Jersey,East,Technology,Machines,9099.930,7,0.0,2365.9818
8488,Arlington,Virginia,South,Technology,Machines,8749.950,5,0.0,2799.9840
6425,Philadelphia,Pennsylvania,East,Technology,Copiers,8399.976,4,0.4,1119.9968

In [102]:
df.nsmallest(10, "Profit")

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
7772,Standard Class,Consumer,United States,Lancaster,Ohio,43130,East,Technology,Machines,4499.985,5,0.7,-6599.9780
683,Same Day,Corporate,United States,Burlington,North Carolina,27217,South,Technology,Machines,7999.980,4,0.5,-3839.9904
9774,Standard Class,Consumer,United States,San Antonio,Texas,78207,Central,Office Supplies,Binders,2177.584,8,0.8,-3701.8928
3011,Standard Class,Home Office,United States,Louisville,Colorado,80027,West,Technology,Machines,2549.985,5,0.7,-3399.9800
4991,Standard Class,Corporate,United States,Chicago,Illinois,60653,Central,Office Supplies,Binders,1889.990,5,0.8,-2929.4845
3151,First Class,Consumer,United States,Newark,Ohio,43055,East,Technology,Machines,1799.994,2,0.7,-2639.9912
5310,First Class,Consumer,United States,Houston,Texas,77095,Central,Office Supplies,Binders,1525.188,6,0.8,-2287.7820
9639,Second Class,Consumer,United States,Concord,North Carolina,28027,South,Furniture,Tables,4297.644,13,0.4,-1862.3124
1199,Standard Class,Consumer,United States,Houston,Texas,77041,Central,Office Supplies,Binders,1088.792,4,0.8,-1850.9464
2697,Standard Class,Home Office,United States,Jacksonville,Florida,32216,South,Technology,Machines,22638.480,6,0.5,-1811.0784

In [103]:
df.shape

(9977, 13)

In [104]:
df.to_csv("Cleaned_SampleSuperstore.csv", index=False)
print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!